name: run_hotels_backend

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17

      - name: Start Docker - Database Container & Compile Application
        run: |
          docker-compose up -d
      - name: Test Application with Maven
        run: |
          mvn test
      - name: Upload Coverage Raport from Jacoco to Codacy
        env:
          CODACY_API_TOKEN: ${{ secrets.CODACY_API_TOKEN }}
          CODACY_ORGANIZATION_PROVIDER: ${{ secrets.CODACY_ORGANIZATION_PROVIDER }}
          CODACY_USERNAME: ${{ secrets.CODACY_USERNAME }}
          CODACY_PROJECT_NAME: ${{ secrets.CODACY_PROJECT_NAME }}
        run: |
          mvn jacoco:report
          cd target && cd site && cd jacoco
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r jacoco.xml
